# Use an existing docker image as base
FROM node:alpine

WORKDIR /app

# Download and install a dependency
COPY ./package.json ./
RUN npm install --registry https://registry.npmjs.org
COPY ./ ./

# Tell the image what to do when it start as a container
CMD ["npm", "run", "start"] 